# Generated by Django 5.2.5 on 2025-08-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="cached_velocity",
            field=models.FloatField(default=0),
        ),
    ]
